name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - 'frontend/**'
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push the Docker image
      run: |
        TAG=$(date +%s)
        docker build ./frontend --file ./frontend/Dockerfile --tag germancruzpallares/temperaturas-frontend:$TAG
        docker push germancruzpallares/temperaturas-frontend:$TAG
        echo "NEW_TAG=$TAG" >> $GITHUB_ENV

    - name: Update Kubernetes manifests
      run: |
        FILE_PATH=$(find . -name "frontend-k8s.yaml" | head -n 1)
        if [ -z "$FILE_PATH" ]; then
          echo "ERROR: frontend-k8s.yaml not found"
          exit 1
        fi
        echo "Updating file: $FILE_PATH"
        sed -i "s|image: germancruzpallares/temperaturas-frontend:1771610361
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add "$FILE_PATH"
        git diff --staged --quiet || git commit -m "Update frontend image tag to ${NEW_TAG}"
        git push origin main